import { Icon } from "@raycast/api";

import { COMMAND_NAME, PAGINATION_SIZE } from "@/constants";

import type { SearchBarAccessoryItem, SearchBarAccessoryCommandName } from "@/types";

const CONFLUENCE_SEARCH_CONTENT_FILTERS: SearchBarAccessoryItem[] = [
  {
    value: "default",
    title: "All Content",
    query: "",
    icon: Icon.MagnifyingGlass,
  },
  {
    value: "viewed_recently",
    title: "Viewed Recently",
    query: `id in recentlyViewedContent(${PAGINATION_SIZE}, 0)`,
    icon: Icon.Eye,
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Viewed Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "created_by_me",
    title: "Created by Me",
    query: "creator = currentUser()",
    icon: Icon.Person,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created desc",
    sectionTitle: ({ fetchedCount, totalCount }) => `Created by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "contributed_by_me",
    title: "Contributed by Me",
    query: "contributor = currentUser()",
    icon: Icon.Pencil,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "lastModified desc",
    sectionTitle: ({ fetchedCount, totalCount }) => `Contributed by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "mentions_me",
    title: "Mentions Me",
    query: "mention = currentUser()",
    icon: Icon.AtSymbol,
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Mentions Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "my_favourites",
    title: "My Favourites",
    query: "favourite = currentUser()",
    icon: Icon.Star,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "favourite desc",
    sectionTitle: ({ fetchedCount, totalCount }) => `My Favourites (${fetchedCount}/${totalCount})`,
  },
  {
    value: "watched_by_me",
    title: "Watched by Me",
    query: "watcher = currentUser()",
    icon: Icon.Eye,
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Watched by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "title_only",
    title: "Title Only",
    query: "",
    icon: Icon.Text,
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/text ~ "/g, 'title ~ "'),
  },
];

const CONFLUENCE_SEARCH_SPACE_FILTERS: SearchBarAccessoryItem[] = [
  {
    value: "default",
    title: "All Space",
    query: "",
    icon: Icon.MagnifyingGlass,
  },
  {
    value: "personal_space",
    title: "Personal Space",
    query: "space.type = personal",
    icon: Icon.Person,
    logicOperator: "AND",
  },
  {
    value: "global_space",
    title: "Global Space",
    query: "space.type = global",
    icon: Icon.Globe,
    logicOperator: "AND",
  },
  {
    value: "favourite_space",
    title: "Favourite Space",
    query: "space.type = favourite",
    icon: Icon.Star,
    logicOperator: "AND",
  },
];

const JIRA_SEARCH_ISSUE_FILTERS: SearchBarAccessoryItem[] = [
  {
    value: "default",
    title: "All Issue",
    query: "",
    icon: Icon.MagnifyingGlass,
  },
  {
    value: "full_text_search",
    title: "Text Search",
    query: "",
    icon: Icon.Text,
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/summary ~ "/g, 'text ~ "'),
  },
  {
    value: "my_open_issues",
    title: "My Open Issues",
    query: "assignee = currentUser() AND resolution = Unresolved",
    icon: Icon.Circle,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "priority DESC, updated DESC, created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `My Open Issues (${fetchedCount}/${totalCount})`,
  },
  {
    value: "open_issues",
    title: "Open Issues",
    query: "resolution = Unresolved",
    icon: Icon.Circle,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC, priority DESC, created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Open Issues (${fetchedCount}/${totalCount})`,
  },
  {
    value: "assigned_to_me",
    title: "Assigned to Me",
    query: "assignee = currentUser()",
    icon: Icon.Person,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Assigned to Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "reported_by_me",
    title: "Reported by Me",
    query: "reporter = currentUser()",
    icon: Icon.Person,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Reported by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "created_recently",
    title: "Created Recently",
    query: "created >= -1w",
    icon: Icon.Clock,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Created Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "updated_recently",
    title: "Updated Recently",
    query: "updated >= -1w",
    icon: Icon.Clock,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Updated Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "resolved_recently",
    title: "Resolved Recently",
    query: "resolutiondate >= -1w",
    icon: Icon.CheckCircle,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Resolved Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "viewed_recently",
    title: "Viewed Recently",
    query: "issuekey in issueHistory()",
    icon: Icon.Eye,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "lastViewed DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Viewed Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "watched_by_me",
    title: "Watched by Me",
    query: "watcher = currentUser()",
    icon: Icon.Eye,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Watched by Me (${fetchedCount}/${totalCount})`,
  },
];

export const SEARCH_BAR_ACCESSORY_CONFIGS = {
  [COMMAND_NAME.CONFLUENCE_SEARCH_CONTENT]: CONFLUENCE_SEARCH_CONTENT_FILTERS,
  [COMMAND_NAME.CONFLUENCE_SEARCH_SPACE]: CONFLUENCE_SEARCH_SPACE_FILTERS,
  [COMMAND_NAME.JIRA_SEARCH_ISSUE]: JIRA_SEARCH_ISSUE_FILTERS,
} as const satisfies Record<SearchBarAccessoryCommandName, SearchBarAccessoryItem[]>;
